CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(25) NOT NULL,
  "password" varchar(10) NOT NULL,
  "age" int NOT NULL,
  "role" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar(100) NOT NULL,
  "category" int NOT NULL,
  "course_video" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(45) UNIQUE NOT NULL,
  "url" varchar(45) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "course_level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int NOT NULL,
  "level" int NOT NULL,
  "teacher" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" int NOT NULL,
  "course" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("course_video") REFERENCES "course_video" ("id");

CREATE TABLE "courses_course_level" (
  "courses_id" int,
  "course_level_course" int,
  PRIMARY KEY ("courses_id", "course_level_course")
);

ALTER TABLE "courses_course_level" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_course_level" ADD FOREIGN KEY ("course_level_course") REFERENCES "course_level" ("course");


CREATE TABLE "level_course_level" (
  "level_id" int,
  "course_level_level" int,
  PRIMARY KEY ("level_id", "course_level_level")
);

ALTER TABLE "level_course_level" ADD FOREIGN KEY ("level_id") REFERENCES "level" ("id");

ALTER TABLE "level_course_level" ADD FOREIGN KEY ("course_level_level") REFERENCES "course_level" ("level");


CREATE TABLE "teacher_course_level" (
  "teacher_id" int,
  "course_level_teacher" int,
  PRIMARY KEY ("teacher_id", "course_level_teacher")
);

ALTER TABLE "teacher_course_level" ADD FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");

ALTER TABLE "teacher_course_level" ADD FOREIGN KEY ("course_level_teacher") REFERENCES "course_level" ("teacher");


CREATE TABLE "courses_users_courses" (
  "courses_id" int,
  "users_courses_course" int,
  PRIMARY KEY ("courses_id", "users_courses_course")
);

ALTER TABLE "courses_users_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_users_courses" ADD FOREIGN KEY ("users_courses_course") REFERENCES "users_courses" ("course");


CREATE TABLE "users_users_courses" (
  "users_id" int,
  "users_courses_name" int,
  PRIMARY KEY ("users_id", "users_courses_name")
);

ALTER TABLE "users_users_courses" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "users_users_courses" ADD FOREIGN KEY ("users_courses_name") REFERENCES "users_courses" ("name");


CREATE TABLE "roles_users" (
  "roles_id" int,
  "users_role" int,
  PRIMARY KEY ("roles_id", "users_role")
);

ALTER TABLE "roles_users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "roles_users" ADD FOREIGN KEY ("users_role") REFERENCES "users" ("role");


INSERT INTO categories (category) VALUES ('Front-End'), ('Back-End');
INSERT INTO level (level) VALUES ('Basic'), ('Intermediate'), ('Advanced');
INSERT INTO teacher (teacher) VALUES ('Andres'), ('Ian');
INSERT INTO roles (role) VALUES ('Student'), ('Teacher'), ('Admin');

INSERT INTO course_video (title, url) VALUES ('React Basic', 'http://reactbasic');
INSERT INTO course_video (title, url) VALUES ('React Intermediate', 'http://reactintermediate');
INSERT INTO course_video (title, url) VALUES ('React Advanced', 'http://reactadvanced');
INSERT INTO course_video (title, url) VALUES ('Node Js Basic', 'http://nodejsbasic');
INSERT INTO course_video (title, url) VALUES ('Node Js Intermediate', 'http://nodejsintermediate');
INSERT INTO course_video (title, url) VALUES ('Node Js Advanced', 'http://nodejsadvanced');

INSERT INTO users (name, email, password, age, role) VALUES ('Roberto', 'rob@gmail.com', 123456, 30, 1);
INSERT INTO users (name, email, password, age, role) VALUES ('Diana', 'diana@gmail.com', 563247, 29, 1);
INSERT INTO users (name, email, password, age, role) VALUES ('Ian', 'ian@academlo.com', 756489, 35, 2);
INSERT INTO users (name, email, password, age, role) VALUES ('Leonel', 'leo@academlo.com', 789562, 32, 3);

INSERT INTO courses (title, description, category, course_video) VALUES ('React Intermediate', 'Learn Intermediate React', 1, 2);
INSERT INTO courses (title, description, category, course_video) VALUES ('Node Js Basic', 'Learn Basic Node Js', 2, 4);
INSERT INTO courses (title, description, category, course_video) VALUES ('Node Js Advanced', 'Learn Advanced Node Js', 2, 6);

INSERT INTO course_level (course, level, teacher) VALUES (1, 2, 1), (2, 1, 2), (3, 3, 2);

INSERT INTO users_courses (name, course) VALUES (1, 2), (2, 1);